openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    Це API для керування контактами та користувачами.
tags:
  - name: Auth
    description: Реєстрація, логін, оновлення токенів, скидання пароля
  - name: Contacts
    description: CRUD операції для контактів
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-hw50.onrender.com
paths:
  /contacts:
    $ref: ../swagger/paths/contacts/contacts.yaml
  /contacts/{contactId}:
    $ref: ../swagger/paths/contacts/{contactId}.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer